### PR TITLE
Search property by short_code

### PR DESCRIPTION
**Pull request by danangmassandy**
This is part of #1420 - adding property short code in the search result and enable search by property short code.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 50 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 0 sec

**Comment by LunaAsefaw** [comment]
@danangmassandy currently I cannot search by name or code. Is my workflow incorrect or something is wrong with the function?

https://github.com/kartoza/sawps/assets/90245715/ea39c2e7-5840-448b-a277-1b38af44276c

**Comment by danangmassandy** [comment]
I think the search on map needs to use the session that has filter selected organisations because current implementation is just to search from current active organisation.
You can confirm this logic by trying to search in Upload Data tab Luna.
I will update the search by selected organisations once I am back on Sanbi.

**Pull request merged**
