### PR TITLE
Patch ecosystem type org page

### PR DESCRIPTION
**Pull request by tinashechiraya**

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by dimasciput** [comment]
Hi @tinashechiraya , please add description and screenshots in the PR

**Comment by tinashechiraya** [comment]
[Screencast from 18-08-23 07:29:08.webm](https://github.com/kartoza/sawps/assets/70011086/68f7e30b-4f54-4bd8-bb90-3298f80e2a5b)

**Comment by tinashechiraya** [comment]
[Screencast from 18-08-23 07:32:51.webm](https://github.com/kartoza/sawps/assets/70011086/9f366335-f47a-4383-8ac8-5a07cc22427a)
@dimasciput please note ecosystem type is not available when I am on local host it just shows holding cname . but when the ecosystem is available it will be appended to the table

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Pull request merged**
