### PR TITLE
Add province labels layer

### PR DESCRIPTION
**Pull request by danangmassandy**
Add province labels table + update the styles. cc: @Jeremy-Prior 
This is for #850.

Preview:
Screenshot_4664

Screenshot_4665

Note: once merged, I'll ask @tharanathkartoza to change tegola conf and restart the tegola service.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@danangmassandy please fix the migration error

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 26 min

**Comment by danangmassandy** [comment]
> @danangmassandy please fix the migration error

I have fixed the migration @dimasciput

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

**Pull request merged**
