### PR TITLE
Fix validation in annual population form

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for https://github.com/kartoza/sawps/issues/1189.
Preview validation:
Screenshot_4728

All validation errors:
Screenshot_4729

Validation for data upload excel:
Screenshot_4733

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 40 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 25 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

**Comment by LunaAsefaw** [comment]
@danangmassandy the validation for area works but the total count still accepts 0,  please also restrict it to take values greater than 0

**Pull request merged**
