### PR TITLE
Add missing mkdocstring

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1716

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 53 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 2 sec

**Review by Jeremy-Prior — CHANGES_REQUESTED** [review]
Paths in mkdocstrings files look good, just one spelling correction that we both missed

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 12 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 35 sec

**Review by Jeremy-Prior — APPROVED** [review]
Docs LGTM

Unsure about the changes in the `django_project` directory

**Comment by Jeremy-Prior** [comment]
@dimasciput Please review the files changed in the `django_project` directory

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 58 sec

**Pull request merged**
