### PR TITLE
Feature add search in admin

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #1459

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 9 sec

**Comment by ketankartoza** [comment]
@dimas I have taken extra time because of bellow points.
1. I have no data for all the tables in my local so I have created multiple data in local.
2. I have tested each search functionality with different different fields.
3. I got 1 bug in the existing code I have also fixed it.
4. Some amount of time is consumed in discussion as well.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 5 sec

**Comment by dimas** [comment]
Can you guys please type in `@dimasciput` in full because github keeps notifying me of a project I have zero relation to...
Thanks

**Comment by ketankartoza** [comment]
> Can you guys please type in `@dimasciput` in full because github keeps notifying me of a project I have zero relation to... Thanks

Okay @dimasciput.
Do my points justify the time?

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 19 sec

**Pull request merged**
