### PR TITLE
Documentation: Corrections

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
- Minor corrections from issues Luna found
- Other corrections I have noticed were needed (e.g. formatting)

Will leave as draft until all other docs PRs are merged

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 48 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 18 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 11 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 42 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 48 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 2 sec

**Comment by Jeremy-Prior** [comment]
Full docs site building and serving on my fork:
https://jeremy-prior.github.io/sawps/

**Review by amyburness — APPROVED** [review]
This looks good

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 55 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 46 sec

**Pull request merged**
