### PR TITLE
add transparency to Area Available Line chart

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #2055.
Preview:
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

**Comment by dimasciput** [comment]
@danangmassandy The chart is difficult to see. Perhaps you could add more transparency to the area available for each species?

**Comment by danangmassandy** [comment]
how about this @dimasciput? I add more the transparency from 0.4 to 0.25

image

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 46 sec

**Pull request merged**
