### PR TITLE
feature/1721: Add multiple species filter on reports

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1721 
[Kazam_screencast_00059.webm](https://github.com/kartoza/sawps/assets/7352963/73b775f9-e0d6-4d0b-a253-57b3b26f6ea8)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 20 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 54 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 38 sec

**Pull request merged**
