### PR TITLE
integration PDF download

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #760

Before : 
Screenshot 2023-08-17 at 11 36 41 AM
After :
Screenshot 2023-08-17 at 11 37 31 AM

### CODE REVIEW

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts and share the pdf output

**Comment by ketankartoza** [comment]
@dimasciput Sure

**Comment by ketankartoza** [comment]
[metrics (15).pdf](https://github.com/kartoza/sawps/files/12376753/metrics.15.pdf)
@dimasciput Here is the downloaded pdf file

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Comment by dimasciput** [comment]
image
image

The text and the charts are squashed and don't look good. Perhaps you need to set the height of the element.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 32 min

**Comment by dimasciput** [comment]
@ketankartoza can you share the updated pdf? Please also fix the conflicts

**Comment by ketankartoza** [comment]
@dimasciput Here is the updated pdf file 
[metricsGraph.pdf](https://github.com/kartoza/sawps/files/12426630/metricsGraph.pdf)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 30 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 30 min

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts, and then you can merge it

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

**Pull request merged**
