### PR TITLE
Update error message

### LINKED ISSUE #1263: Update error message in frontend
After uploading species file, the error message showing in page doesn't work properly.

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #1263

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by dimasciput** [comment]
@Fanevanjanahary thanks, I'm going to merge this one, since I don't think there will be an issue.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 44 sec

**Pull request merged**
