### PR TITLE
Fix/1408 age group chart

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1408 
Demo:
[Kazam_screencast_00045.webm](https://github.com/kartoza/sawps/assets/7352963/3824d744-e9cf-46e5-9a7d-5d9cfdb154f1)
Screenshot from 2023-11-02 14-58-41
Screenshot from 2023-11-02 14-58-27

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 10 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 58 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 53 sec

**Comment by LunaAsefaw** [comment]
@zamuzakki The goal of this chart is to show total population for a specific year by age and gender so that is why it is a stacked chart. So all of the data accumulated shows us the count at the bottom as total but we also see them divided by their age and gender (hence I can see there is a total of 800 for 2023)
But when people upload data where only total is given but gender is not revealed, it goes to the 'unspecified' category. However, the unspecified category is taking up a bar of its own, instead of being stacked for their respective years. For example, in the image below, these are both for 2019 but they are shown on different bars. Please add unspecified on the same bar too so users can get overall count.
image
image

**Pull request merged**
