### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #1022 and #1025

Before:-
image

After:-
image

Before:-
image

After:-
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 1 sec

**Pull request merged**
