### PR TITLE
Feature/1434 annual population owned species update

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1434 #1407 #1365 
- [x] Move Owned Species fields to Annual Population, but the Owned Species and its relation to Annual Population and Annual Population Per Acitvity is not yet removed. 
- [x] Add FK from Annual Population Per Acitvity to Annual Population
- [x] Update all code utilising owned species to directly use Annual Population's field.
- [x] Allow update area available for species per year (shown below).
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 1 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 6 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 44 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 12 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 13 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 47 sec

**Pull request merged**
