### PR TITLE
Fix property code importer

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for:

- https://github.com/kartoza/sawps/issues/1420
- https://github.com/kartoza/sawps/issues/1419

Preview of #1420 (also added short_code in Right side bar and in online form page):
Screenshot_4730

Preview updated validation using short_code:
Screenshot_4731

Preview of #1419:
Screenshot_4742

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 29 sec

**Comment by dimasciput** [comment]
@danangmassandy please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 23 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 18 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 7 sec

**Pull request merged**
