### PR TITLE
Tinashechiraya patch 10

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 04-10-2023 03:02:46.webm](https://github.com/kartoza/sawps/assets/70011086/35fda924-f3cb-4d6a-a256-335dec50501e)

Description:
now selecting an organisation will fetch the properties for that property
selecting multiple organisations will fetch the properties for those organisations
user roles have been enforced on the organisation and properties selections

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 2 min 9 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 15 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 39 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 42 min

**Pull request merged**
