### PR TITLE
Improve loading in frontend

### PR DESCRIPTION
**Pull request by dimasciput**
#1916

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by dimasciput** [comment]
Fixes https://github.com/kartoza/sawps/issues/1880

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Review by danangmassandy — APPROVED** [review]
LGTM, thanks

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec

**Pull request merged**
