### PR TITLE
Added radio button with collapse

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #1006 and for #1020.

Before:-
image
image

After:- 
image
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 20 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 37 sec

**Comment by LunaAsefaw** [comment]
@ketankartoza it does not automatically collapse when a selection is made 

Uploading collapse.mp4…

**Pull request merged**
