### PR TITLE
Fixes for filter deselect

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #1211 

https://github.com/kartoza/sawps/assets/138113337/c2aa8728-98a8-4353-a67d-5385ad153bff

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 11 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Comment by dimasciput** [comment]
Hi @ketankartoza , this isn't good UX practice. Since it's a dropdown and not a checkbox, users typically don't expect to be able to unselect it. We should consider adding an "Unspecified" or similar option as the first choice.

cc @amyburness @LunaAsefaw

**Comment by ketankartoza** [comment]
> Hi @ketankartoza , this isn't good UX practice. Since it's a dropdown and not a checkbox, users typically don't expect to be able to unselect it. We should consider adding an "Unspecified" or similar option as the first choice.
> 
> cc @amyburness @LunaAsefaw

As per instructions from @amyburness, I have completed the task.

**Comment by amyburness** [comment]
@dimasciput and @ketankartoza I want to follow up with @timlinux on this as he originally said that we should make this a simple dropdown. I feel like a standardization for all the dropdowns would be the best option because we now have a mismatch of checkbox dropdowns and simple dropdowns let's discuss in the planning meeting today.

**Comment by dimasciput** [comment]
@ketankartoza I'm going to close this ticket, since we are going to use different approach. Thanks.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 6 sec

**Pull request closed without merging**
