### PR TITLE
Simple filter UI

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #1074 

Before:-
image

After:- 
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 20 min

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 11 sec

**Pull request merged**
