### PR TITLE
Feature/1241: Refactor Data Table

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1241 
What I did:
- [x] Use Serializer for Data Returns
- [x] Reduce Code Redundancy
- [x] Update frontend components to parse and render the newly serialized data outputs correctly

[Kazam_screencast_00028.webm](https://github.com/kartoza/sawps/assets/7352963/44fc6e46-5268-4a9c-af6b-315304bdb34d)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Comment by dimasciput** [comment]
@zamuzakki can you add screenshots please, for the new tables

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 52 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Comment by dimasciput** [comment]
@zamuzakki please resolve the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 2 sec

**Pull request merged**
