### PR TITLE
Remove unnecessary file

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #2040

### CODE REVIEW

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by Jeremy-Prior** [comment]
@ketankartoza please address the conflicts when you're ready

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 39 sec

**Pull request merged**
