### PR TITLE
Chart UI updates

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 04-10-2023 01:16:13.webm](https://github.com/kartoza/sawps/assets/70011086/8b9bc46d-f461-4c3c-a4de-57c20fdd987d)

Description:
the dropdown shadow has been removed
a legend has been added to each chart
axis labels/titles have been added to each chart
legend label names are arranged alpahebetically 
charts share the same height and width
horizontal scroll has been removed 
all the requirements of ticket #1147 and #1091 have been addressed
I have removed the donut charts for now since they will be rearranged and styled in a seperate ticket

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 18 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 36 sec

**Comment by tinashechiraya** [comment]
@dimasciput its failing at build docker images

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 30 sec

**Pull request merged**
