### PR TITLE
Feature organisation request

### PR DESCRIPTION
**Pull request by DONOTFORGET-BYTE**

### CODE REVIEW

**Comment by DONOTFORGET-BYTE** [comment]
@dimasciput I'm not sure why it was showing old commits but I have created a fresh branch with just the fixes for yesterday

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by danangmassandy** [comment]
@DONOTFORGET-BYTE could you attach screenshot of emails being sent? thanks

**Review by danangmassandy — COMMENTED** [review]
@DONOTFORGET-BYTE could you attach screenshot of emails being sent? thanks

**Comment by DONOTFORGET-BYTE** [comment]
> @DONOTFORGET-BYTE could you please attach screenshot of emails being sent? thanks

Screenshot 2023-07-14 155955
this is what it looked like before the changes requested by Amy which are in the this pr just adjusting the wording and adding the logo. then the one for the organisation request looks like this too but no register button since its just a notification email

**Review by danangmassandy — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Pull request merged**
