### PR TITLE
allow to upload excel file

### LINKED ISSUE #825: Updates to annual population table
changes in purple

Image

### LINKED ISSUE #943: Alert messages for data upload using csv
There is an inconsistency between the alert messages when users upload data using csv (users are sometimes alerted and sometimes nothing happens). Please account for these scenarios:
After finishing processing the file, it will display both the error and success files.

Image

In the error file, there will be a new field called “error_message” to indicate what the error is for that row.

Image

### LINKED ISSUE #944: Inconsistency between current django admin tables and the template
Sampling size unit is not part of the table now. This is replaced by sampling effort coverage

Image

Image

Certainties is now renamed to Population estimate certainty and is a dropdown of numeric numbers from 1-10.

Count method can be dropped, is replaced by population estimate category
Image

Please add 'sort_order' column to sampling effort coverage

Image

### LINKED ISSUE #1004: Allow users to upload excel files
Currently, users upload data using CSVs.  Please enable excel uploads as well

### LINKED ISSUE #1064: Update error message if the values of compulsory fields are empty
The values of compulsory fields in template shouldn't be empty

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #1004 

fixes #944 
image
open-property

fixes #943

fixes #825

fixes #1064
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 39 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 37 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 10 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 56 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 20 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 11 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 34 sec

**Pull request merged**
