### PR TITLE
Get only Species data 

### PR DESCRIPTION
**Pull request by ketankartoza**
Only show the taxon data which taxon_rank is  equals to Species into the filter side panel

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Comment by dimasciput** [comment]
@ketankartoza, could you please clean up your commit history? It currently includes old commits from a different PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Comment by ketankartoza** [comment]
I am closing this PR because of unmanaged commit history. 

New PR [here](https://github.com/kartoza/sawps/pull/647)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 25 sec

**Pull request closed without merging**
