### PR TITLE
hide edit action when user is not the data owner

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #1717.
The edit icon is now hidden when user is not the owner. cc: @LunaAsefaw 
Preview:
image

This is also for #1727 - applies to online form only. (I will submit another PR for edit from csv/excel upload)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 43 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 37 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 28 sec

**Pull request merged**
