### PR TITLE
Download data

### LINKED ISSUE #1313: Updates to the download data CSV  functionality
image
- [ ] update this button to say DOWNLOAD DATA
- [ ] When the user clicks the button they should be given the option to download a CSV or a XLSX file 
- [ ] The download should be only the filtered data shown on the users screen (but include all columns even those off by default like species common name.

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #1313

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 24 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 8 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 38 sec

**Comment by dimasciput** [comment]
@Fanevanjanahary could you add more tests please?

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 22 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 17 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 18 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 10 sec

**Comment by LunaAsefaw** [comment]
@Fanevanjanahary when I test this on staging, nothing happens. The buttons are active but nothing happens when clicked on so please test that and please make sure these buttons are pivoted to the screen as mentioned in #1025

**Pull request merged**
