### PR TITLE
Remove filter_start_year from map query

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #1580 part of #1574

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 53 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 22 sec

**Comment by danangmassandy** [comment]
@dimasciput I also added more test to species upload changes from PR #1581 because coverage checked is failed.

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 33 sec

**Pull request merged**
