### PR TITLE
Documentation landing page

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1279 #1281

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 12 min

**Comment by dimasciput** [comment]
@Jeremy-Prior please check

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec

**Pull request merged**
