### PR TITLE
Feature parent farm

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #1674.

I decided to store the layer name and id to the Parcel table, this is to make consistent when getting the list of parcel from a property with selected parcels during property creation. Also to make the property detail API faster. Once this PR is deployed, we need to trigger action 'patch_parcel_sources' from admin page to patch existing parcels.
TODO after PR is merged:

- [ ] Run action patch_parcel_sources from parcel listing in admin page.
- [x] Ask Tharanath to update tegola.conf

Update UI in the Parcel selection during property creation (cc: @LunaAsefaw @amyburness):
Screenshot_4792

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 49 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 4 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 39 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 8 min 6 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 58 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 37 sec

**Pull request merged**
