### PR TITLE
Docs: Multiple Updates

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
- Mainly updates to the user guide where content was missing, still WIP
- merged the upstream into main before making PR

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 5 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 16 sec

**Comment by dimasciput** [comment]
@Jeremy-Prior can you fix the conflicts please

**Comment by Jeremy-Prior** [comment]
@dimasciput fixed the conflict

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 6 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 12 sec

**Pull request merged**
