### PR TITLE
fix/1629: Move property size VS total area charts to trends

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1629 
- [x] Remove Age Group Bar Chart
- [x] Move Total Area Vs Available Area Api Chart to Trends page.

Screenshot from 2023-11-23 11-02-39

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 41 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 36 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 46 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 30 sec

**Pull request merged**
