### PR TITLE
Documentation charts guide

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #2063 

- [x]  Add the screenshots of all charts.
- [x]  Add the content in the charts guide.
- [x]  Add the screenshots of the trends.
- [x]  Add the content to the trends guide.
- [x]  Test on local.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 20 min

**Review by Jeremy-Prior — CHANGES_REQUESTED** [review]
Just need to correct the Americanised use of 'z' instead of 's'

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 30 sec

**Pull request merged**
