### PR TITLE
Add alert message in upload

### LINKED ISSUE #795: Upload csv function should check values
Currently, the upload function takes in data and updates reference tables. For example, if I record 'ABC' in species and upload the CSV, 'ABC' is added to the species table. Instead, upon upload, the system needs to check all the foreign key records and ensure that they are values in the parent table. If they are not or there is a misspelled reference, an error message needs to pop up explaining where the error is, eg: 'record 'ABC' is not found in the species table. Look at the species spreadsheet to see all recorded species' or something along those lines

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #795 

- [x] Checking the Taxon

image

- [x] Checking the property
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 17 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 32 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Pull request merged**
