### PR TITLE
Fix inconsistent number of properties in charts

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 22-10-2023 10:29:14.webm](https://github.com/kartoza/sawps/assets/70011086/6a5be996-0cdf-469b-a5c5-a4eb3b0fd895)

Description:
I have updated the density bar chart to calculate the density using this formual: (species_annual_population_total / area_available_to_species)
I have updated the density bar to work with the year filters 
I have update the total area available to a species chart to work with the year filters

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 54 sec

**Comment by dimasciput** [comment]
Done in another PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 6 sec

**Pull request closed without merging**
