### PR TITLE
Documentation:  Multiple Updates

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
- User guide updates for current state of site
- Adding header text for help desk
- Checking all docs build
- Fixing broken relative links
- Update screenshots

The site builds locally and just before this PR I merged the upstream with my main.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 37 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 44 sec

**Comment by Jeremy-Prior** [comment]
@dimasciput please review

- I had to update the metrics.py file. I created a new file and copied all the content from the original file so it has the same content as before but the original file was causing an issue.
    image
- I then also had to update the requirements.txt to allow for the uuid implementation for the helpdesk

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 1 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 33 sec

**Pull request merged**
