### PR TITLE
Adjust charts styling

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description:

I have adjusted the height and width of other charts so they match
I have updated the position of the download button ,it will now be fixed in the bottom right corner
I have adjusted the property type chart to use property type name in legend labels and tooltip to show property name

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Comment by LunaAsefaw** [comment]
@tinashechiraya where are these values being pulled from because it says private several times and is there a difference in colour between the last two items in the legend?

image
Additionally, if the bars are colour-coded by property type, then what is on the x-axis? The diagram initially had years in the legend because we have a stacked bar graph showing property types on the x-axis
image

**Comment by tinashechiraya** [comment]
@LunaAsefaw the reason it has multiple privates is because those are for different properties . Since each property has a single property type ,its showing the property type name for each property you selected . On the colors It ran out of available colors since there are a lot of properties being plotted on the graph ,but this can be resolved .

then since this is a Total area per property type chart ,where it fetches area allocated for each property there aren't any dates related to this type of chart . A property only has a created at date which never changes ?

**Comment by LunaAsefaw** [comment]
then that means the x-axis is currently properties, not property types right?

if that's the case, that needs to be adjusted. This is to see what property types exist in an aggregated way, we don't need to see which property is of which property type, does that make sense?

Oh I see, year is listed when species information is registered. Alright let's discuss this during the meeting today

**Pull request merged**
