### PR TITLE
Feature/979 data consumer filter

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #979 
Report/Data
report

Trends
trends

Charts
charts

Map
map

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 35 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 50 sec

**Review by danangmassandy — APPROVED** [review]
Data consumer checks looks okay and as superuser should not have data consumer specific permissions so superuser can see everything to property level.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 29 sec

**Comment by dimasciput** [comment]
@zamuzakki please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 8 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 43 sec

**Pull request merged**
