### PR TITLE
Feature/789

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #789 
**Page layout and exported PDF:**
[Acinonyx jubatus - reports-3.pdf](https://github.com/kartoza/sawps/files/13361153/Acinonyx.jubatus.-.reports-3.pdf)

**Exported Excel:**
[data_report_excel.zip](https://github.com/kartoza/sawps/files/13361167/data_report_excel.zip)

**Exported CSV:**
[data_report_csv.zip](https://github.com/kartoza/sawps/files/13361169/data_report_csv.zip)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 9 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 46 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 38 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 42 sec

**Pull request merged**
