### PR TITLE
Org in profile and url

### PR DESCRIPTION
**Pull request by tinashechiraya**

### CODE REVIEW

**Comment by tinashechiraya** [comment]
[Screencast from 18-08-23 01:08:04.webm](https://github.com/kartoza/sawps/assets/70011086/a99db2db-0722-4901-80d6-ba71e0c2fe11)

**Comment by tinashechiraya** [comment]
[Screencast from 18-08-23 01:21:24.webm](https://github.com/kartoza/sawps/assets/70011086/2d151f47-36a8-46c2-a7c1-6da388bea9b2)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Pull request merged**
