### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
- Adding Sandhya's latest content
- Reordering some sections per feedback
- Adjusting image names
- Adding to user guide
- Still adding header text to all documentation

The docs site serves locally without warnings.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 22 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 1 sec

**Comment by Jeremy-Prior** [comment]
@dimasciput Please review and then merge if okay.
The docs site builds locally and I pulled and merged the latest upstream just before converting from a draft.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 17 sec

**Pull request merged**
