### PR TITLE
Update the login page doc

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1949 

https://github.com/kartoza/sawps/assets/138113337/04fb6ce4-510e-4db2-8383-b55ec1ad8d4e

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 59 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 50 sec

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 9 sec

**Pull request merged**
