### PR TITLE
Update 2fa page and underline titles

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 12-09-2023 21:33:32.webm](https://github.com/kartoza/sawps/assets/70011086/6fc19508-2372-4ae3-a9f5-19c50f367e4f)

Description
every modal on the page contains a page divider in green
every cancel,close or delete button is red by default and incases where there is delete and cancel the delete is grey
removed the frame around current 2fa method

[Screencast from 12-09-2023 22:01:47.webm](https://github.com/kartoza/sawps/assets/70011086/9459de3a-dd87-433e-8008-55ce714522bc)

 Description 
All delete modals have been updated to have the same styling (delete modal on 2fa,users,reminders and notifications)

### CODE REVIEW

**Comment by dimasciput** [comment]
Screenshot 2023-09-13 at 8 45 58 AM

The padding at the top and bottom needs to be the same size.

**Comment by dimasciput** [comment]
Screenshot 2023-09-13 at 8 47 44 AM

Don't change the text to black during the onclick or onfocus events of the button; just make the button slightly darker.

**Review by dimasciput — APPROVED** [review]
Please see my comments above

**Review by dimasciput — CHANGES_REQUESTED** [review]
Please see my comments above

**Comment by dimasciput** [comment]
@tinashechiraya any updates on this?

**Comment by tinashechiraya** [comment]
@dimasciput I have resolved this 
[Screencast from 14-09-2023 21:55:28.webm](https://github.com/kartoza/sawps/assets/70011086/155c9496-91d5-4d9b-802e-32b66815d58a)

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

**Pull request merged**
