### PR TITLE
Feature notifications page

### PR DESCRIPTION
**Pull request by DONOTFORGET-BYTE**

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by dimasciput** [comment]
@DONOTFORGET-BYTE please convert it to a PR before I review it.

**Comment by dimasciput** [comment]
@DONOTFORGET-BYTE please convert it to  a PR

**Comment by DONOTFORGET-BYTE** [comment]
> @DONOTFORGET-BYTE please convert it to a PR

Alright let me resolve the conflicts first

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 18 min

**Pull request closed without merging**
