### PR TITLE
Fix/1767: Organisation Manager Add

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1767

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 51 sec

**Comment by dimasciput** [comment]
@zamuzakki please fix the test

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 23 sec

**Review by danangmassandy — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 48 sec

**Pull request merged**
