### PR TITLE
Feature/1360-1373 chart year filter

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1373 #1360
- Charts are now showing data based on filtered years.

Screen Shot 2023-11-03 at 09 55 11-fullpage

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 58 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 41 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 32 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 21 sec

**Pull request merged**
