### PR TITLE
Fix density bar chart

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 10-10-2023 14:23:27.webm](https://github.com/kartoza/sawps/assets/70011086/aa5c64a8-6853-456e-ab50-46af454d6668)

Description:
chart can now pull the data and render it on the chart
the chart follows the same styling from the other charts and the graph matrix document
I have also update the property type chart to have unique colors for bars

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 37 sec

**Comment by LunaAsefaw** [comment]
@tinashechiraya the logic has been fixed but the colours are still inconsistent. We cannot have two greys but one orange while the other graph is another colour. It will make the user want to find a legend as to why those two are grey while the others are other colours
image

**Pull request merged**
