### PR TITLE
Feature data scientist

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #979 

Screenshot 2023-09-15 at 4 41 07 PM

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 29 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

**Comment by LunaAsefaw** [comment]
@ketankartoza the organisation filter works, thanks but the UI is very unfriendly. Please fix the alignment of the names of organisations and do similar editing as the ones proposed for property  #1043

**Pull request merged**
