### PR TITLE
Add more error in row, check constraint

### LINKED ISSUE #1264: Check the error in the other column in upload file.
For now, the error file returns only one error for each row. Check the other error in the other column.

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #1264

image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 56 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 48 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 40 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@Fanevanjanahary please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by dimasciput** [comment]
@Fanevanjanahary there is error in the test, can you fix it

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 4 sec

**Pull request merged**
