### PR TITLE
Updated user role permission

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1925 

The reason for time is the creation of a user diagram.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 19 sec

**Review by Jeremy-Prior — APPROVED** [review]
LGTM.

@dimasciput, is it okay to merge despite the playwright test failing?

**Comment by ketankartoza** [comment]
> LGTM.
> 
> @dimasciput, is it okay to merge despite the playwright test failing?

@Jeremy-Prior @dimasciput Please do not merge this PR because the client has changed his mind again. I will create new PR today. this PR is useless now.

**Comment by ketankartoza** [comment]
> LGTM.
> 
> @dimasciput, is it okay to merge despite the playwright test failing?

@Jeremy-Prior @dimasciput Please do not merge this PR because the client has changed his mind again. I will create new PR today. this PR is useless now.

**Comment by Jeremy-Prior** [comment]
@ketankartoza, do you want to close this PR then?

**Comment by LunaAsefaw** [comment]
@ketankartoza yes

**Comment by ketankartoza** [comment]
Client changed permissions.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 44 sec

**Pull request closed without merging**
