### PR TITLE
Feature search map

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #806
Preview:
Peek 2023-09-19 08-11

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 24 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 58 sec

**Comment by LunaAsefaw** [comment]
@danangmassandy This function is meant to search areas/location/streets so users who want to record new properties can navigate to the specific area #806 so when the user types in three letters, the combobox should show areas in South Africa that start with the three letters so the user can choose that and navigate to that area. The users can filter by registered property using the property filter

**Comment by LunaAsefaw** [comment]
@tinashechiraya see above

**Comment by LunaAsefaw** [comment]
@amyburness Actually I am rethinking the purpose of this functionality now. It worked before when data upload was here but now Data upload is on its own so if users are searching areas to record new properties, that is a functionality that happens on the page below
image

What exactly do they search on the map tab?

**Pull request merged**
