### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #746

Before:-
image

After:-
image

### CODE REVIEW

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflict

**Comment by ketankartoza** [comment]
> @ketankartoza please fix the conflict

Hi @dimasciput I am working on the UI changes as suggested in new UI. I will push the code again.

**Comment by ketankartoza** [comment]
@dimasciput Please merge this PR. After discussion i will add UI changes in next PR if needed.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

**Pull request merged**
