### PR TITLE
Feature/1536 report responsive

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #1536 
Screenrecord:
[Kazam_screencast_00053.webm](https://github.com/kartoza/sawps/assets/7352963/51dcfd49-d245-4fe1-94b6-1c776ba3dfba)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 43 sec

**Comment by dimasciput** [comment]
@zamuzakki, it looks great! However, may I suggest that we don't need a hide/show filter button? Can we simply use the filter header to toggle the filter panel?

**Comment by zamuzakki** [comment]
This is the updated UI @dimasciput 
[Kazam_screencast_00055.webm](https://github.com/kartoza/sawps/assets/7352963/0b5d3c5d-25c1-494d-b192-ed0426a2f193)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 46 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 56 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 45 sec

**Comment by dimasciput** [comment]
@zamuzakki hmm it seems the first behaviour is better. Instead of a sliding animation, could you update it to use a toggle similar to the first version, but keep the hamburger button?

**Comment by zamuzakki** [comment]
@dimasciput I've removed the animation
[Kazam_screencast_00056.webm](https://github.com/kartoza/sawps/assets/7352963/94ee843d-4e07-4505-a391-71d2d9be8e01)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 59 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 35 sec

**Pull request merged**
