### PR TITLE
Refer scientific name on charts

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1665 

image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 43 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 57 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 12 sec

**Comment by danangmassandy** [comment]
@ketankartoza sorry about this, I also added the scientific name and year to the charts in my PR #1810 that has been merged. I asked Luna to do quick review during meeting and she said I should add scientific name+year too. Could you check whether we still need this PR? I use selectedSpecies from the filter to display the name so I don't change anything in the backend.

**Comment by ketankartoza** [comment]
> @ketankartoza sorry about this, I also added the scientific name and year to the charts in my PR #1810 that has been merged. I asked Luna to do quick review during meeting and she said I should add scientific name+year too. Could you check whether we still need this PR? I use selectedSpecies from the filter to display the name so I don't change anything in the backend.

@danangmassandy I have checked on the staging site and all the charts have scientific names. I think we do not need this PR now. @LunaAsefaw please close this PR. Thanks!!

**Comment by ketankartoza** [comment]
@amyburness can I close this PR? as the task is already done and we do not need to merge this into the main branch.

**Comment by ketankartoza** [comment]
The issue was resolved in another PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 16 sec

**Pull request closed without merging**
