### PR TITLE
Tinashechiraya patch 8

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 11-09-2023 14:32:46.webm](https://github.com/kartoza/sawps/assets/70011086/2a05d9a8-dee8-4b1e-abbc-51ac01481fb5)

Description:
removed the upload tab from the tabs on the maps page
created upload data link in the navibar
renamed map to explore
moved remember me text to the left
changed const vars to normal var to fix error on edit reminders

### CODE REVIEW

**Comment by dimasciput** [comment]
image

Please place the "Remember Me" text in the center, with the checkbox to its right.

**Review by dimasciput — CHANGES_REQUESTED** [review]
please see my comment above

**Comment by tinashechiraya** [comment]
Screenshot from 2023-09-12 07-24-21

@dimasciput i have place it on the center

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 25 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

**Comment by LunaAsefaw** [comment]
@tinashechiraya great work.  Please link the second 'Upload data' button as well because it takes us to map when it is clicked
image

**Pull request merged**
