### PR TITLE
Fix subpopulation fields

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #1525:

- [x] Add adult_total field to excel upload
- [x] Make subpopulation fields editable in the online form

Preview:
Screenshot_4762

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 48 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 47 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 23 sec

**Pull request merged**
