### PR TITLE
Add user docs on upload csv data

### LINKED ISSUE #754: Documentation of features: Faneva
Please make user manual documentation of the features you have made similar to the example below adding them to the documentation site using markdown files.
if unsure ask @Fanevanjanahary or @Jeremy-Prior in slack.
image

### PR DESCRIPTION
**Pull request by Fanevanjanahary**
fixes #754

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 29 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

**Pull request merged**
