### PR TITLE
Change DO_NOTHING to CASCADE

### PR DESCRIPTION
**Pull request by zamuzakki**
Using `on_delete=models.DO_NOTHING` causes IntegrityError. 
I update it to `on_delete=models.CASCADE` and add filters to Property admin page.
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 3 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 12 sec

**Comment by LunaAsefaw** [comment]
I am now able to drop those fields, thanks @zamuzakki 
image

**Pull request merged**
