### PR TITLE
Fix data table API

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #1195 

Before:- 
image

After:-
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Comment by dimasciput** [comment]
Hi @ketankartoza, what I meant was to use a serializer for the property. This way, you won't need to use extends.

Refer to @tinashechiraya's code for an example: https://github.com/kartoza/sawps/blob/main/django_project/frontend/api_views/national_statistic.py#L105.

**Comment by ketankartoza** [comment]
> Hi @ketankartoza, what I meant was to use a serializer for the property. This way, you won't need to use extends.
> 
> Refer to @tinashechiraya's code for an example: https://github.com/kartoza/sawps/blob/main/django_project/frontend/api_views/national_statistic.py#L105.

okay @dimasciput

**Comment by ketankartoza** [comment]
> > Hi @ketankartoza, what I meant was to use a serializer for the property. This way, you won't need to use extends.
> > Refer to @tinashechiraya's code for an example: https://github.com/kartoza/sawps/blob/main/django_project/frontend/api_views/national_statistic.py#L105.
> 
> okay @dimasciput

@dimasciput Can do it like this?
"open": property.open.name if property.open else None
I need to change both the frontend and backend code if I do it like Tinashe did.

**Comment by dimasciput** [comment]
@ketankartoza I'm going to merge it for now, but we will refactor the codes

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 9 sec

**Pull request merged**
