### PR TITLE
Year restrictions

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #1015 and #1017

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 22 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 2 min 23 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 9 min 53 sec

**Comment by LunaAsefaw** [comment]
@ketankartoza there is a glitch here. when I select a year greater than the second year, it sends me back to 1960 (which is fine) but when I put in a year less than the second year, it still sends me back

https://github.com/kartoza/sawps/assets/90245715/d64fad53-c1a9-43f7-b0ce-341a394c1ee1

**Pull request merged**
