### PR TITLE
add switch 3d icon to map nav control

### PR DESCRIPTION
**Pull request by danangmassandy**
This is for #1610.
Preview:

### CODE REVIEW

**Comment by dimasciput** [comment]
@danangmassandy perhaps make it darker when selected?

**Comment by danangmassandy** [comment]
updated @dimasciput
Selected:
Screenshot_4802

Not selected:
Screenshot_4803

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 54 sec

**Pull request merged**
