### PR TITLE
Fixes for data tab filter

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #1005 

Screenshot 2023-09-15 at 5 17 33 PM
Screenshot 2023-09-15 at 5 21 14 PM

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 25 min

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@ketankartoza please fix the conflicts

**Comment by ketankartoza** [comment]
> @ketankartoza please fix the conflicts

Okay.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 30 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 27 min

**Pull request merged**
