### PR TITLE
Fixes horizontal scroll for reports

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for #1146 #855 

Screenshot 2023-10-05 at 9 11 41 PM

Screenshot 2023-10-05 at 9 12 05 PM

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

**Comment by dimasciput** [comment]
@ketankartoza have you make the text aligned to left?

**Comment by ketankartoza** [comment]
> @ketankartoza have you make the text aligned to left?

Yes @dimasciput

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 12 min

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

**Pull request merged**
