### PR TITLE
Species pop age group and total area charts

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 05-10-2023 10:05:32.webm](https://github.com/kartoza/sawps/assets/70011086/2cefae9a-ec75-4495-954f-0b9cf42dc58d)

Description
the old charts have bee cleared and only new ones will be added as they are completed
population per age group and total area available vs area available for species have been added
charts require a property selected 
the sidebar panel filters work on the charts ,a selection will cause new data to be fetched
the charts are using the styles from graph matrix document (colours etc)

### CODE REVIEW

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@tinashechiraya please fix the conflict

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 47 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Pull request merged**
