### PR TITLE
patch: make chart responsive to year filter #1373

### PR DESCRIPTION
**Pull request by tinashechiraya**
[Screencast from 22-10-2023 11:29:40.webm](https://github.com/kartoza/sawps/assets/70011086/049b5ca1-d0d7-4109-9aba-9ea8d2f87891)

Description:
I have made the charts responsive with the years filter

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

**Comment by dimasciput** [comment]
Done in https://github.com/kartoza/sawps/pull/1513

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 1 sec

**Pull request closed without merging**
